name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
#     strategy:
#       fail-fast: false
#       matrix:
# # List of keymap json files to build
#         file:
#         - keebio_iris_rev4_layout_mine.json
# End of json file list

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: SonixQMK/qmk_firmware
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}

    - name: Copy Keymap.c
      run: cp -f users/${{ github.actor }}/keymap.c keyboards/keychron/k6/keymaps/ansi/

    # - name: Copy Rules.mk
    #   run: cp -f users/${{ github.actor }}/keyboards/keebio/stick/rules.mk keyboards/keebio/stick/

    # - name: Set options
    #   run: |
    #     echo "#define CIRQUE_PINNACLE_SPI_CS_PIN B6" >> keyboards/keebio/stick/config.h
    #     echo "#define CIRQUE_PINNACLE_CURVED_OVERLAY" >> keyboards/keebio/stick/config.h
    #     echo "#define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_RELATIVE_MODE" >> keyboards/keebio/stick/config.h
    #     echo "#define CIRQUE_PINNACLE_TAP_ENABLE" >> keyboards/keebio/stick/config.h
    #     echo "#define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE" >> keyboards/keebio/stick/config.h
    #     echo "#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_2X" >> keyboards/keebio/stick/config.h
    #     echo "#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE" >> keyboards/keebio/stick/config.h
    #     # echo "#define POINTING_DEVICE_ROTATION_90" >> keyboards/keebio/stick/config.h
    #     # fix for rotation, https://github.com/qmk/qmk_firmware/issues/21010
    #     # sed -i '101s/.*/        feedconfig1 |= HOSTREG__FEEDCONFIG1__FEED_ENABLE | HOSTREG__FEEDCONFIG1__X_DATA_INVERT | HOSTREG__FEEDCONFIG1__Y_DATA_INVERT;/' drivers/sensors/cirque_pinnacle.c

    - name: Build firmware
      # run: qmk compile "users/${{ github.actor }}/${{ matrix.file }}"
      # run: qmk compile -kb keebio/iris/rev4 -km loquillo
      run: qmk compile -kb keychron/k6/rgb -km ansi

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: keychron_k6_${{ github.actor }}
        path: |
          *.hex
          *.bin
          *.uf2