name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
#     strategy:
#       fail-fast: false
#       matrix:
# # List of keymap json files to build
#         file:
#         - keebio_iris_rev4_layout_mine.json
# End of json file list

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: SonixQMK/qmk_firmware
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}

    - name: Copy Keymap.c
      run: cp -f users/${{ github.actor }}/keymap.c keyboards/keychron/k6/keymaps/ansi/

    # - name: Copy ansi.c
    #   run: cp -f users/${{ github.actor }}/ansi.c keyboards/keychron/k6/rgb/ansi/ansi.c

    - name: Set options
      run: |
        echo "#define FORCE_NKRO" >> keyboards/keychron/k6/rgb/config.h
    #     echo "#define BOOTMAGIC_LITE_ROW 0" >> keyboards/keychron/k6/rgb/config.h
    #     echo "#define BOOTMAGIC_LITE_COLUMN 0" >> keyboards/keychron/k6/rgb/config.h
    #     sed -i 's/MAGIC_KEYCODE_ENABLE = yes/MAGIC_KEYCODE_ENABLE = no/' keyboards/keychron/k6/rgb/rules.mk
    #     sed -i 's/MAGIC_ENABLE = yes/MAGIC_ENABLE = no/' keyboards/keychron/k6/rgb/rules.mk
    #     sed -i 's/NKRO_ENABLE = yes/NKRO_ENABLE = no/' keyboards/keychron/k6/rgb/rules.mk
    #     sed -i 's/WAIT_FOR_USB = yes/WAIT_FOR_USB = no/' keyboards/keychron/k6/rgb/rules.mk
    #     sed -i 's/KEYBOARD_SHARED_EP = yes/KEYBOARD_SHARED_EP = no/' keyboards/keychron/k6/rgb/rules.mk
    #     sed -i 's/RGB_MATRIX_ENABLE = yes/RGB_MATRIX_ENABLE = no/' keyboards/keychron/k6/rgb/rules.mk
    #     cat keyboards/keychron/k6/rgb/rules.mk

    - name: Build firmware
      # run: qmk compile "users/${{ github.actor }}/${{ matrix.file }}"
      # run: qmk compile -kb keebio/iris/rev4 -km loquillo
      run: qmk compile -kb keychron/k6/rgb -km ansi

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: keychron_k6_${{ github.actor }}
        path: |
          *.hex
          *.bin
          *.uf2